### ISSUE TITLE
If page changes height, this script fails

### ISSUE THREAD

**Issue by blasto333** [EnzoMartin/Sticky-Element#1]
If something is expanded or collapsed on the page such as when an image loads or an element is displayed (when it was hidden to start), the sticky container does not work.

Do you have a workaround?

**Comment by DanBoSlice** [comment]
Looks like this repository is no longer active, which is sad because it is a really helpful plugin. So if there is a fix for this, it would be nice if it was implemented.

**Comment by EnzoMartin** [comment]
Honestly didn't think anyone would actually use this. If you are though, I can look at it this weekend and do some bug fixes

**Comment by EnzoMartin** [comment]
I'll push out an update to `1.0.0` tonight

**Comment by EnzoMartin** [comment]
Should be all set now :+1: 

I've also published it to NPM
