### ISSUE TITLE
Recreating a fixed Sidebar

### ISSUE THREAD

**Issue by vilbht** [EnzoMartin/Sticky-Element#2]
Hi there,

Just found this plugin. Any tips on how to create this effect seen in the sidebar?
https://www.format.com/magazine/resources/photography/10-steps-to-building-your-perfect-online-portfolio

There's 3 divs in the sidebar:
- There is 1 constantly sticky element
- Under that is a second element that becomes sticky fixed on scroll
- Under that is a 3rd element, which on scroll takes the place of the 2nd element, while the 2nd element fades away..

Thanks!

**Comment by EnzoMartin** [comment]
Just off the top of my head, you could make 2 divs with fixed heights with a stickied element in them, and then when each of the element's `sticky-hit-bottom` events fire, you can modify the element's CSS to hide it

**Comment by vilbht** [comment]
thanks @EnzoMartin . Will try this out later today and circle back to get your thoughts!
