### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by abydahana** [EnzoMartin/Sticky-Element#3]
Hello, thank you for this great plugin. But it need more improvement to make this work in all browsers. I tried this plugin and works well in Chrome, but not work in Firefox. Do you have any clue to make this work in Firefox?

Thank you...

**Comment by EnzoMartin** [comment]
Fixed, thanks for reporting that! I checked IE & Edge just to be sure as well

**Comment by abydahana** [comment]
Great. Thank you very much!
