### ISSUE TITLE
In mobile phones and Mac OS trembles when scrolling and falls behind

### ISSUE THREAD

**Issue by makissm21** [EnzoMartin/Sticky-Element#5]
How can this be remedied?
[http://test.cmski.ru/](url)

**Comment by EnzoMartin** [comment]
You can't, it's because it's not using `position: fixed`

**Comment by EnzoMartin** [comment]
I recommend you use https://developers.google.com/web/updates/2012/08/Stick-your-landings-position-sticky-lands-in-WebKit
