### ISSUE TITLE
how to use events in your code

### ISSUE THREAD

**Issue by GuenniWeb** [EnzoMartin/Sticky-Element#7]
are there demos showing the difference?
Thanks

**Comment by GuenniWeb** [comment]
is there a way to set it to off for screens smaller a given value.
For responsive case  of floating columns.

**Comment by EnzoMartin** [comment]
I've added an example for using the events, but there's no support in the plugin for responsive handling, however you can do that with code and use the `toggleFreeze` method to stop/start it

**Comment by GuenniWeb** [comment]
Thanks for your reply.

Your code is very nice  - but if I want to stick a column which in responsive case floats to the left, this is not the best.

I tried to setup in my functions.php a on (load , resize)   function with window width rules but it seems that your script hampers in a way the fireing of resize function.    I’m no expert – so It would be nice on your script to have a “breaking point” where the script stopps working.

 

______________________________________________________________________________

 

mfG
Weber 

digitale Dienstleistungen 

___________________________

 

USt.Id: DE248027935 
Ludwig-Schopp-Straße 27 
53117 Bonn 
Tel 0228 / 9768293 

Mobil 0151 / 26381720

Fax  0228 / 9768296
 <mailto:info@guenterweber.com> info@guenterweber.com
 <https://guenterweber.com/> https://guenterweber.com

 <https://webers-webdesign.de/> https://webers-webdesign.de

 

 

Von: Enzo Martin [mailto:notifications@github.com] 
Gesendet: Dienstag, 31. Oktober 2017 20:41
An: EnzoMartin/Sticky-Element
Cc: GuenniWeb; Author
Betreff: Re: [EnzoMartin/Sticky-Element] how to use events in your code (#7)

 

I've added an example for using the events, but there's no support in the plugin for responsive handling, however you can do that with code and use the toggleFreeze to stop/start it
